### ISSUE TITLE
After following your recent and updated work we failed to load the client? could you please tell us whats wrong with us?

### ISSUE THREAD

**Issue by adil25** [vincentberaud/Minecraft-Reinforcement-Learning#4]
/home/adil/anaconda3/bin/python /home/adil/pycharm/pycharm-2017.2.4/helpers/pydev/pydevd.py --multiproc --qt-support=auto --client 127.0.0.1 --port 45121 --file /home/adil/Downloads/Minecraft-Reinforcement-Learning-master/DRQN_vs_DQN_minecraft.py
pydev debugger: process 1374 is connecting

Connected to pydev debugger (build 172.4343.24)
/home/adil/anaconda3/lib/python3.6/importlib/_bootstrap.py:205: RuntimeWarning: compiletime version 3.5 of module 'tensorflow.python.framework.fast_tensor_util' does not match runtime version 3.6
  return f(*args, **kwds)
[2019-03-30 21:14:24,557] Making new env: MinecraftBasic-v0
/home/adil/anaconda3/lib/python3.6/site-packages/minecraft_py-0.0.2-py3.6.egg/minecraft_py/Malmo/Minecraft
Traceback (most recent call last):
  File "/home/adil/pycharm/pycharm-2017.2.4/helpers/pydev/pydevd.py", line 1599, in <module>
    globals = debugger.run(setup['file'], None, None, is_module)
  File "/home/adil/pycharm/pycharm-2017.2.4/helpers/pydev/pydevd.py", line 1026, in run
    pydev_imports.execfile(file, globals, locals)  # execute the script
  File "/home/adil/pycharm/pycharm-2017.2.4/helpers/pydev/_pydev_imps/_pydev_execfile.py", line 18, in execfile
    exec(compile(contents+"\n", file, 'exec'), glob, loc)
  File "/home/adil/Downloads/Minecraft-Reinforcement-Learning-master/DRQN_vs_DQN_minecraft.py", line 50, in <module>
    skip_steps = 0) #Movements modified to a faster convergence
  File "/home/adil/anaconda3/lib/python3.6/site-packages/gym_minecraft-0.0.2-py3.6.egg/gym_minecraft/envs/minecraft_env.py", line 114, in init
    self.mc_process, port = minecraft_py.start()
  File "/home/adil/anaconda3/lib/python3.6/site-packages/minecraft_py-0.0.2-py3.6.egg/minecraft_py/__init__.py", line 77, in start
    raise EOFError("Minecraft process finished unexpectedly")
EOFError: Minecraft process finished unexpectedly
Backend Qt5Agg is interactive backend. Turning interactive mode on.

**Comment by ClementRomac** [comment]
Hello Adil,

It appears that your error comes from the lauching of Malmo (from minecraft_py).

Have you used Malmo since February ?
If not there were changes in it that causes old installs to fail launching. Here is the issue related : [https://github.com/Microsoft/malmo/issues/795](issue). You can check if this is your case by going in the 'Minecraft' folder in your Malmo path and run the launchClient.bat. If you have the same issue you can try the solution provided [https://github.com/Microsoft/malmo/issues/795#issuecomment-464209772](here).

Let me know if that's the case,
Clément

**Comment by adil25** [comment]
From Malmo's /Minecraft folder the client run and load successfully using the terminal, however, we we run your file DRQN_vs_DQN_minecraft.py in both terminal and in pycharm editor so it gives this below error. we have a GPU tower and a Laptop GPU both with Ubuntu 16.4 LTS. The GPU tower was configured in 2018 and your all previous and recent files (code) runs on it, however these do not run on the GPU laptop configured just a couple of days before.
/home/adil/anaconda3/bin/python /home/adil/Downloads/Minecraft-Reinforcement-Learning-master/DRQN_vs_DQN_minecraft.py
/home/adil/anaconda3/lib/python3.6/importlib/_bootstrap.py:205: RuntimeWarning: compiletime version 3.5 of module 'tensorflow.python.framework.fast_tensor_util' does not match runtime version 3.6
  return f(*args, **kwds)
[2019-03-31 12:55:27,640] Making new env: MinecraftBasic-v0
/home/adil/minecraft-py/minecraft_py/Malmo/Minecraft
Traceback (most recent call last):
  File "/home/adil/Downloads/Minecraft-Reinforcement-Learning-master/DRQN_vs_DQN_minecraft.py", line 50, in <module>
    skip_steps = 0) #Movements modified to a faster convergence
  File "/home/adil/anaconda3/lib/python3.6/site-packages/gym_minecraft-0.0.2-py3.6.egg/gym_minecraft/envs/minecraft_env.py", line 114, in init
    self.mc_process, port = minecraft_py.start()
  File "/home/adil/anaconda3/lib/python3.6/site-packages/minecraft_py-0.0.2-py3.6.egg/minecraft_py/__init__.py", line 80, in start
    raise EOFError("Minecraft process finished unexpectedly")
EOFError: Minecraft process finished unexpectedly

**Comment by ClementRomac** [comment]
Hi Adil,

Sorry for that late answer. 
Do only the recent files fail to run on your new laptop or also the old ones ? By reading your error, it doesn't seem that it comes from our code but rather from Malmo as minecraft_py can't run it.

Clément

**Comment by adil25** [comment]
Thanks for your reply, However, neither the new ones nor the old ones (files) works on my laptop.
    On Friday, April 5, 2019, 4:21:34 PM GMT+8, Clément ROMAC <notifications@github.com> wrote:  
 
 
Hi Adil,

Sorry for that late answer.
Do only the recent files fail to run on your new laptop or also the old ones ? By reading your error, it doesn't seem that it comes from our code but rather from Malmo as minecraft_py can't run it.

Clément

**Comment by ClementRomac** [comment]
If neither our old files nor the new ones work, I guess your issue doesn't come from our work. 
Consequently, I can't really help you. I would advise you to check your Malmo/Minecraft-py installations and find where the issue is comming from as the stack trace you sent me doesn't show the real error.

Sorry I can't help you more,
Clément
